### ISSUE TITLE
bgpkit-broker-backend integration

### ISSUE THREAD

**Issue by egecemkirci** [bgpkit/bgpkit-broker#8]
I am trying to understand how to use bgpkit-broker locally. I believe what bgpkit-broker-backend achieves is to substitute the remote MRT databases with a local copy. Following this, should I replace reference URLs (as seen in the below) with the `"0.0.0.0:18888"` to make bgpkit-broker talk to the local API instead of the remote one? Or is it more intricate than this?
https://github.com/bgpkit/bgpkit-broker/blob/25b3c3c4ed5d373245efb105bc47bda4a1ac478e/src/lib.rs#L301

Thank you for your support.

**Comment by digizeph** [comment]
When you initiate a broker object, you will need to provide a endpoint. See example here https://github.com/bgpkit/bgpkit-broker/blob/25b3c3c4ed5d373245efb105bc47bda4a1ac478e/src/lib.rs#L20

You just need to put the local one there.

**Comment by egecemkirci** [comment]
Yes, it worked. Thanks a lot for the response!
